import io
import whisper
from flask import Flask, render_template, request, send_file, session, jsonify

import json
import os
import re
from pathlib import Path
from datetime import datetime, timezone, timedelta

import requests
from dotenv import load_dotenv
import resend

from youtube_transcript_api import YouTubeTranscriptApi

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from html import escape as html_escape
from flask_wtf.csrf import CSRFProtect


# Lazy-loaded Whisper model (loads once on first use)
_whisper_model = None

def get_whisper_model():
    global _whisper_model
    if _whisper_model is None:
        _whisper_model = whisper.load_model("tiny.en")
    return _whisper_model


app = Flask(__name__)
app.secret_key = os.getenv("FLASK_SECRET_KEY", "dev-meetingmind-secret-key")
app.config['MAX_CONTENT_LENGTH'] = 25 * 1024 * 1024  # 25MB
app.config['WTF_CSRF_ENABLED'] = True

# Initialize CSRF protection
csrf = CSRFProtect(app)


def _load_env():
    # Repo-level `.env` is one directory above `MeetingMind/`.
    repo_root = Path(__file__).resolve().parent.parent
    load_dotenv(repo_root / ".env")


# Load env once at startup for gunicorn/production
_load_env()


def _parse_gemini_json(text: str) -> dict:
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Try ```json ... ``` blocks.
    fenced = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", text, flags=re.IGNORECASE)
    if fenced:
        return json.loads(fenced.group(1))

    # Fallback: slice to the first/last JSON object.
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        return json.loads(text[start : end + 1])

    raise ValueError("Could not parse model output as JSON.")


def _is_valid_email(value: str) -> bool:
    value = value.strip()
    if not value:
        return False
    # Simple email validation. We intentionally keep it permissive.
    return re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", value) is not None


def _build_email_body(person_responsible: str, action_item: str, deadline: str, priority: str = "Low") -> str:
    import urllib.parse
    from datetime import datetime, timedelta
    import re

    person = person_responsible.strip() or "there"
    deadline_text = deadline.strip() or "Not specified"
    action_text = action_item.strip() or "Not specified"

    # Build Google Calendar link
    title = urllib.parse.quote(action_text)
    details = urllib.parse.quote(
        f"Assigned to: {person}\nDeadline: {deadline_text}\nPriority: {priority}\nGenerated by MeetingMind"
    )

    # Try to parse date from deadline text
    start_date = None
    date_patterns = [
        (r"(\d{4}-\d{2}-\d{2})", "%Y-%m-%d"),
        (r"(\d{2}/\d{2}/\d{4})", "%d/%m/%Y"),
        (r"(\d{1,2}/\d{1,2}/\d{4})", "%m/%d/%Y"),
        (r"(\d{2}-\d{2}-\d{4})", "%d-%m-%Y"),
    ]
    for pat, fmt in date_patterns:
        m = re.search(pat, deadline)
        if m:
            try:
                start_date = datetime.strptime(m.group(1), fmt)
                break
            except ValueError:
                continue

    if not start_date:
        start_date = datetime.now(timezone.utc) + timedelta(days=7)

    end_date = start_date + timedelta(days=1)
    fmt_date = lambda d: d.strftime("%Y%m%d")
    dates = f"{fmt_date(start_date)}/{fmt_date(end_date)}"

    calendar_link = (
        f"https://calendar.google.com/calendar/render?action=TEMPLATE"
        f"&text={title}&details={details}&dates={dates}"
    )

    return f"""Hi {person},

You have been assigned an action item from a recent meeting:

Action Item : {action_text}
Deadline    : {deadline_text}
Priority    : {priority}

Add this directly to your Google Calendar with one click:
{calendar_link}

Please let me know if you have any questions.

Best regards,
MeetingMind
"""


def send_action_item_emails(action_items: list[dict], emails: list[str]) -> tuple[int, int]:
    api_key = os.getenv("RESEND_API_KEY")
    if not api_key:
        raise RuntimeError("RESEND_API_KEY is missing from .env file.")
    
    # Credentials used only for this request, never persisted
    resend.api_key = api_key
    
    to_pairs = []
    for idx, item in enumerate(action_items):
        email = (emails[idx] if idx < len(emails) else "").strip()
        if email and _is_valid_email(email):
            to_pairs.append((email, item))
    
    sent_count = 0
    skipped_count = len(action_items) - len(to_pairs)
    
    if not to_pairs:
        return 0, skipped_count
    
    for to_email, item in to_pairs:
        body = _build_email_body(
            person_responsible=str(item.get("person_responsible", "")),
            action_item=str(item.get("action_item", "")),
            deadline=str(item.get("deadline", "")),
            priority=str(item.get("priority", "Low")),
        )
        try:
            resend.Emails.send({
                "from": "MeetingMind <onboarding@resend.dev>",
                "to": to_email,
                "subject": "Action item assigned to you — MeetingMind",
                "text": body,
            })
            sent_count += 1
        except Exception as e:
            print(f"Resend error for {to_email}: {e}")
            skipped_count += 1
    
    return sent_count, skipped_count


def extract_action_items(transcript: str) -> list[dict]:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError("GROQ_API_KEY is missing. Please set it in the root .env file.")

    system_prompt = """
You extract structured action items from meeting transcripts.

Extract action items (specific next steps). For each action item, include:
- person_responsible: who is responsible (if stated)
- deadline: the due date / time frame (if stated)
- priority: urgency level (High or Low) based on:
  * High = urgent, time-sensitive, or critical for business
  * Low = important but not immediately urgent, or nice to have

Return ONLY valid JSON (no markdown, no commentary) with the exact schema:
{
  "action_items": [
    {
      "action_item": "...",
      "person_responsible": "...",
      "deadline": "...",
      "priority": "High|Low"
    }
  ]
}

Rules:
- Use empty string "" when a field is not explicitly stated.
- For priority, analyze urgency and importance from context.
- If there are no action items, return {"action_items": []}.
""".strip()

    user_prompt = f"Transcript:\n{transcript}".strip()

    url = "https://api.groq.com/openai/v1/chat/completions"
    payload = {
        "model": "llama-3.3-70b-versatile",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.2,
        "max_tokens": 512,
    }

    headers = {"Authorization": f"Bearer {api_key}"}
    resp = requests.post(url, headers=headers, json=payload, timeout=60)
    if not resp.ok:
        raise RuntimeError(f"Groq API error {resp.status_code}: {resp.text}")

    data = resp.json()
    content = (
        data.get("choices", [{}])[0]
        .get("message", {})
        .get("content", "")
    )
    if not content:
        raise ValueError("Groq returned empty content; expected JSON.")

    parsed = _parse_gemini_json(content)

    if not isinstance(parsed, dict):
        raise ValueError("AI returned invalid JSON structure.")

    items = parsed.get("action_items") or []
    if not isinstance(items, list):
        raise ValueError("AI returned invalid action_items structure.")

    normalized: list[dict] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        normalized.append(
            {
                "action_item": str(item.get("action_item", "") or ""),
                "person_responsible": str(item.get("person_responsible", "") or ""),
                "deadline": str(item.get("deadline", "") or ""),
                "priority": str(item.get("priority", "Low") or "Low"),
            }
        )
    return normalized


def generate_meeting_summary(transcript: str) -> str:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError("GROQ_API_KEY is missing. Please set it in the root .env file.")

    system_prompt = """
You generate concise meeting summaries from transcripts.

Create a 2-3 sentence summary that captures:
1. Main topics discussed
2. Key decisions made
3. Overall meeting outcome

Keep it brief, clear, and professional. No bullet points, just plain text.
""".strip()

    user_prompt = f"Transcript:\n{transcript}".strip()

    url = "https://api.groq.com/openai/v1/chat/completions"
    payload = {
        "model": "llama-3.3-70b-versatile",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.3,
        "max_tokens": 150,
    }

    headers = {"Authorization": f"Bearer {api_key}"}
    resp = requests.post(url, headers=headers, json=payload, timeout=60)
    if not resp.ok:
        raise RuntimeError(f"Groq API error {resp.status_code}: {resp.text}")

    data = resp.json()
    content = (
        data.get("choices", [{}])[0]
        .get("message", {})
        .get("content", "")
    )
    
    if not content:
        raise ValueError("Groq returned empty content for summary.")
    
    return content.strip()


@app.get("/")
def index():
    # Start fresh for new browser sessions.
    session.pop("transcript", None)
    session.pop("action_items", None)
    return render_template(
        "index.html",
        transcript="",
        action_items=[],
        emails=[],
        error_message=None,
        success_message=None,
        meeting_summary=None,
    )


@csrf.exempt
@app.post("/submit")
def submit():
    transcript = request.form.get("transcript", "").strip()
    action_items: list[dict] = []
    emails: list[str] = []
    error_message = None
    success_message = None
    meeting_summary = None

    if transcript.strip():
        try:
            action_items = extract_action_items(transcript)
            emails = ["" for _ in range(len(action_items))]
            meeting_summary = generate_meeting_summary(transcript)
        except ValueError:
            error_message = (
                "AI returned an invalid response. Please try again with the same transcript."
            )
            emails = []
        except RuntimeError as e:
            error_message = str(e)
            emails = []
        except Exception:
            error_message = "Something went wrong while extracting action items. Please try again."
            emails = []

    # Persist data for PDF export (and fallback if frontend payload is escaped).
    session["transcript"] = transcript
    session["action_items"] = action_items
    session["meeting_summary"] = meeting_summary

    return render_template(
        "index.html",
        transcript=transcript,
        action_items=action_items,
        emails=emails,
        error_message=error_message,
        success_message=success_message,
        meeting_summary=meeting_summary,
    )


@csrf.exempt
@app.post("/send_emails")
def send_emails():
    transcript = request.form.get("transcript", "")
    error_message = None
    success_message = None

    try:
        count_raw = request.form.get("action_item_count", "0").strip()
        count = int(count_raw) if count_raw else 0
    except ValueError:
        count = 0

    action_items: list[dict] = []
    emails: list[str] = []
    for i in range(count):
        action_items.append(
            {
                "action_item": request.form.get(f"action_item_{i}", ""),
                "person_responsible": request.form.get(f"person_responsible_{i}", ""),
                "deadline": request.form.get(f"deadline_{i}", ""),
                "priority": request.form.get(f"priority_{i}", "Low"),
            }
        )
        emails.append(request.form.get(f"email_{i}", ""))

    # Keep session aligned for PDF export.
    session["transcript"] = transcript
    session["action_items"] = action_items
    session["meeting_summary"] = session.get("meeting_summary")  # Preserve meeting summary

    if not action_items:
        error_message = "No action items found to email. Please submit a transcript first."
    else:
        try:
            sent_count, skipped_count = send_action_item_emails(action_items, emails)
            if sent_count > 0:
                success_message = f"✅ Sent {sent_count} email(s) via MeetingMind."
                if skipped_count > 0:
                    success_message += f" Skipped {skipped_count} (missing or invalid email address)."
            else:
                error_message = "No emails were sent. Please enter at least one valid recipient email address."
        except RuntimeError as e:
            if "RESEND_API_KEY" in str(e):
                error_message = "RESEND_API_KEY is not configured. Please add it to .env"
            else:
                error_message = str(e)
        except Exception as e:
            error_message = f"Failed to send emails: {str(e)}"

    return render_template(
        "index.html",
        transcript=transcript,
        action_items=action_items,
        emails=emails,
        error_message=error_message,
        success_message=success_message,
        meeting_summary=session.get("meeting_summary"),
    )


@csrf.exempt
@app.post("/export_pdf")
def export_pdf():
    try:
        transcript = session.get("transcript", request.form.get("transcript", ""))
        action_items = session.get("action_items", [])
        meeting_summary = session.get("meeting_summary", "")

        # Fallback to form payload in case session is missing
        if not isinstance(action_items, list) or not action_items:
            action_items_json = request.form.get("action_items_json", "[]")
            try:
                parsed = json.loads(action_items_json)
                action_items = parsed if isinstance(parsed, list) else []
            except json.JSONDecodeError:
                action_items = []

        if transcript is None:
            transcript = ""

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50,
            title="MeetingMind Report",
        )
        styles = getSampleStyleSheet()
        elements = []

        # Title
        title_style = styles['Title']
        title_style.fontSize = 24
        title_style.textColor = colors.HexColor("#7c3aed")
        title = Paragraph("<b>MeetingMind Report</b>", title_style)
        elements.append(title)
        elements.append(Spacer(1, 24))

        # Meeting Summary section
        if meeting_summary and meeting_summary.strip():
            h2_style = styles['Heading2']
            h2_style.textColor = colors.HexColor("#1e293b")
            h2_style.fontSize = 14
            elements.append(Paragraph("<b>Meeting Summary</b>", h2_style))
            elements.append(Spacer(1, 8))
            summary_style = styles['Normal']
            summary_style.fontSize = 10
            summary_style.textColor = colors.HexColor("#334155")
            elements.append(Paragraph(html_escape(meeting_summary), summary_style))
            elements.append(Spacer(1, 20))

        # Transcript section
        if transcript.strip():
            h2_style = styles['Heading2']
            h2_style.textColor = colors.HexColor("#1e293b")
            h2_style.fontSize = 14
            elements.append(Paragraph("<b>Transcript</b>", h2_style))
            elements.append(Spacer(1, 8))
            transcript_html = html_escape(transcript).replace("\n", "<br/>")
            text_style = styles['Normal']
            text_style.fontSize = 9
            text_style.textColor = colors.HexColor("#475569")
            elements.append(Paragraph(transcript_html, text_style))
            elements.append(Spacer(1, 20))

        # Action Items section
        h2_style = styles['Heading2']
        h2_style.textColor = colors.HexColor("#1e293b")
        h2_style.fontSize = 14
        elements.append(Paragraph("<b>Extracted Action Items</b>", h2_style))
        elements.append(Spacer(1, 12))

        table_data = [["Action Item", "Person Responsible", "Deadline", "Priority"]]
        for item in action_items:
            if not isinstance(item, dict):
                continue
            table_data.append(
                [
                    html_escape(str(item.get("action_item", "") or "Unspecified")),
                    html_escape(str(item.get("person_responsible", "") or "Unspecified")),
                    html_escape(str(item.get("deadline", "") or "Unspecified")),
                    html_escape(str(item.get("priority", "Low") or "Low")),
                ]
            )

        if len(table_data) == 1:
            text_style = styles['Normal']
            text_style.fontSize = 10
            text_style.textColor = colors.HexColor("#64748b")
            elements.append(Paragraph("No action items found for this transcript.", text_style))
        else:
            tbl = Table(
                table_data,
                colWidths=[220, 130, 100, 80],
                repeatRows=1,
            )
            tbl.setStyle(
                TableStyle([
                    # Header styling - Purple matching UI
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#7c3aed")),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, 0), 11),
                    ('ALIGN', (0, 0), (-1, 0), 'LEFT'),
                    ('BOTTOMPADDING', (0, 0), (-1, 0), 14),
                    ('TOPPADDING', (0, 0), (-1, 0), 14),

                    # Body styling
                    ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 1), (-1, -1), 10),
                    ('ALIGN', (0, 1), (-1, -1), 'LEFT'),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),

                    # Grid
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ('LINEBELOW', (0, 0), (-1, 0), 1, colors.HexColor("#7c3aed")),

                    # Padding
                    ('LEFTPADDING', (0, 0), (-1, -1), 10),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 10),
                    ('TOPPADDING', (0, 1), (-1, -1), 10),
                    ('BOTTOMPADDING', (0, 1), (-1, -1), 10),
                ])
            )

            # Zebra rows - alternating colors
            for i in range(1, len(table_data)):
                if i % 2 == 0:
                    tbl.setStyle([
                        ('BACKGROUND', (0, i), (-1, i), colors.HexColor("#f1f5f9"))
                    ])

            elements.append(tbl)

        # Footer
        elements.append(Spacer(1, 30))
        footer_style = styles['Normal']
        footer_style.fontSize = 8
        footer_style.textColor = colors.HexColor("#94a3b8")
        elements.append(Paragraph("Generated by MeetingMind AI", footer_style))

        doc.build(elements)
        buffer.seek(0)

        return send_file(
            buffer,
            as_attachment=True,
            download_name="meetingmind_report.pdf",
            mimetype="application/pdf",
        )
    except Exception as e:
        import traceback
        print(f"PDF Export Error: {str(e)}")
        print(traceback.format_exc())
        return f"Error generating PDF: {str(e)}", 500


@app.post("/export_calendar")
def export_calendar():
    import re
    from datetime import datetime, timedelta

    action_items = session.get("action_items", [])
    if not isinstance(action_items, list):
        action_items = []

    if not action_items:
        data = request.get_json(silent=True) or {}
        action_items = data.get("action_items", [])

    now = datetime.now(timezone.utc)
    now_stamp = now.strftime("%Y%m%dT%H%M%SZ")

    cal_lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//MeetingMind//MeetingMind 1.0//EN",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        "X-MS-OLK-FORCEINSPECTOROPEN:TRUE",
        "X-WR-CALNAME:MeetingMind Action Items",
    ]

    def ics_escape(text: str) -> str:
        text = str(text).strip()
        text = text.replace("\\", "\\\\")
        text = text.replace(";", "\\;")
        text = text.replace(",", "\\,")
        text = text.replace("\r\n", "\\n")
        text = text.replace("\n", "\\n")
        text = text.replace("\r", "\\n")
        return text

    def fold_line(line: str) -> str:
        if len(line.encode("utf-8")) <= 75:
            return line
        result = []
        while len(line.encode("utf-8")) > 75:
            chunk = line[:75]
            while len(chunk.encode("utf-8")) > 75:
                chunk = chunk[:-1]
            result.append(chunk)
            line = " " + line[len(chunk):]
        result.append(line)
        return "\r\n".join(result)

    def parse_date(deadline_raw: str):
        patterns = [
            (r"(\d{4}-\d{2}-\d{2})", "%Y-%m-%d"),
            (r"(\d{2}/\d{2}/\d{4})", "%d/%m/%Y"),
            (r"(\d{1,2}/\d{1,2}/\d{4})", "%m/%d/%Y"),
            (r"(\d{2}-\d{2}-\d{4})", "%d-%m-%Y"),
        ]
        for pat, fmt in patterns:
            m = re.search(pat, deadline_raw)
            if m:
                try:
                    return datetime.strptime(m.group(1), fmt)
                except ValueError:
                    continue
        return None

    for idx, item in enumerate(action_items):
        if not isinstance(item, dict):
            continue

        action      = item.get("action_item", "Action Item") or "Action Item"
        person      = item.get("person_responsible", "") or ""
        deadline_raw = item.get("deadline", "") or ""
        priority_str = item.get("priority", "Low") or "Low"

        event_date = parse_date(deadline_raw) or (now + timedelta(days=7))
        date_str   = event_date.strftime("%Y%m%d")

        outlook_priority = {"High": "1", "Low": "9"}.get(priority_str, "9")

        desc_parts = []
        if person:
            desc_parts.append(f"Assigned to: {person}")
        desc_parts.append(f"Deadline: {deadline_raw if deadline_raw else 'Not specified'}")
        desc_parts.append(f"Priority: {priority_str}")
        desc_parts.append("Generated by MeetingMind")
        description = ics_escape("\\n".join(desc_parts))

        uid = f"meetingmind-{now_stamp}-{idx}@meetingmind.local"

        event_lines = [
            "BEGIN:VEVENT",
            f"UID:{uid}",
            f"DTSTAMP:{now_stamp}",
            f"DTSTART;VALUE=DATE:{date_str}",
            f"DTEND;VALUE=DATE:{date_str}",
            f"SUMMARY:{ics_escape(action)}",
            f"DESCRIPTION:{description}",
            f"PRIORITY:{outlook_priority}",
            f"X-MS-OLK-SENDER:{person if person else 'MeetingMind'}",
            "TRANSP:TRANSPARENT",
            "STATUS:CONFIRMED",
            "CLASS:PUBLIC",
            "END:VEVENT",
        ]
        cal_lines.extend(event_lines)

    cal_lines.append("END:VCALENDAR")

    folded = [fold_line(line) for line in cal_lines]
    ics_content = "\r\n".join(folded) + "\r\n"

    return send_file(
        io.BytesIO(ics_content.encode("utf-8")),
        as_attachment=True,
        download_name="meetingmind_actions.ics",
        mimetype="text/calendar; charset=utf-8",
    )


@app.post("/chat")
def chat():
    """Chat with AI about the meeting transcript."""
    data = request.get_json()
    if not data:
        return jsonify({"success": False, "error": "No data provided"}), 400
    
    transcript = data.get("transcript", "").strip()
    question = data.get("question", "").strip()
    history = data.get("history", [])  # List of {role, content} objects
    
    if not transcript:
        return jsonify({"success": False, "error": "No transcript provided"}), 400
    
    if not question:
        return jsonify({"success": False, "error": "No question provided"}), 400
    
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return jsonify({"success": False, "error": "GROQ_API_KEY not configured"}), 500
    
    system_prompt = "You are a helpful meeting assistant. Answer questions about the meeting transcript provided. Be concise and accurate."
    
    # Build messages array with history
    messages = [{"role": "system", "content": system_prompt}]
    
    # Add conversation history if provided
    if isinstance(history, list) and history:
        for msg in history:
            if isinstance(msg, dict) and "role" in msg and "content" in msg:
                messages.append({"role": msg["role"], "content": msg["content"]})
    
    # Add current question with transcript context
    user_prompt = f"Meeting Transcript:\n{transcript}\n\nQuestion: {question}"
    messages.append({"role": "user", "content": user_prompt})
    
    url = "https://api.groq.com/openai/v1/chat/completions"
    payload = {
        "model": "llama-3.3-70b-versatile",
        "messages": messages,
        "temperature": 0.3,
        "max_tokens": 512,
    }
    
    headers = {"Authorization": f"Bearer {api_key}"}
    
    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=60)
        if not resp.ok:
            return jsonify({"success": False, "error": f"API error: {resp.status_code}"}), 500
        
        data = resp.json()
        answer = (
            data.get("choices", [{}])[0]
            .get("message", {})
            .get("content", "")
            .strip()
        )
        
        if not answer:
            return jsonify({"success": False, "error": "No answer received from AI"}), 500
        
        return jsonify({"success": True, "answer": answer})
    except Exception as e:
        return jsonify({"success": False, "error": f"Failed to get answer: {str(e)}"}), 500


def _extract_video_id(url: str) -> str | None:
    """Extract YouTube video ID from various URL formats."""
    patterns = [
        r'(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/|youtube\.com\/v\/|youtube\.com\/shorts\/)([^&\n?#]+)',
        r'youtube\.com\/watch\?.*v=([^&\n?#]+)',
    ]
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1)
    return None


@app.post("/fetch_youtube")
def fetch_youtube():
    """Fetch transcript from YouTube video URL."""
    data = request.get_json()
    if not data:
        return jsonify({"success": False, "error": "No data provided"}), 400
    
    url = data.get("url", "").strip()
    if not url:
        return jsonify({"success": False, "error": "No URL provided"}), 400
    
    video_id = _extract_video_id(url)
    if not video_id:
        return jsonify({"success": False, "error": "Invalid YouTube URL"}), 400
    
    try:
        ytt_api = YouTubeTranscriptApi()
        fetched = ytt_api.fetch(video_id)
        transcript_text = " ".join([snippet.text for snippet in fetched])
        return jsonify({"success": True, "transcript": transcript_text})
    except Exception as e:
        return jsonify({"success": False, "error": "YouTube is blocking transcript access from this IP. Please copy the transcript manually from YouTube and paste it below."}), 500


@app.post("/transcribe")
def transcribe():
    """Transcribe audio/video file using local OpenAI Whisper model."""
    if "file" not in request.files:
        return jsonify({"success": False, "error": "No file provided"}), 400
    
    file = request.files["file"]
    if not file or file.filename == "":
        return jsonify({"success": False, "error": "No file selected"}), 400
    
    # Check file extension
    allowed_extensions = {".mp3", ".mp4", ".wav", ".m4a"}
    file_ext = os.path.splitext(file.filename)[1].lower()
    if file_ext not in allowed_extensions:
        return jsonify({"success": False, "error": f"Unsupported file format. Allowed: {', '.join(allowed_extensions)}"}), 400
    
    # Save to temp file
    import tempfile
    with tempfile.NamedTemporaryFile(delete=False, suffix=file_ext) as tmp_file:
        tmp_file.write(file.read())
        tmp_path = tmp_file.name
    
    try:
        # Load whisper model and transcribe
        model = get_whisper_model()
        result = model.transcribe(tmp_path)
        transcript = result["text"]
        
        # Clean up temp file
        os.unlink(tmp_path)
        
        if not transcript:
            return jsonify({"success": False, "error": "No transcription returned"}), 500
        
        return jsonify({"success": True, "transcript": transcript})
    
    except Exception as e:
        # Clean up temp file on error
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        return jsonify({"success": False, "error": f"Transcription error: {str(e)}"}), 500


@app.post("/export_csv")
def export_csv():
    """Export action items as professionally formatted Excel file."""
    from openpyxl import Workbook
    from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
    from datetime import datetime
    
    action_items = session.get("action_items", [])
    meeting_summary = session.get("meeting_summary", "")
    
    # Fallback to form payload
    if not isinstance(action_items, list) or not action_items:
        action_items_json = request.form.get("action_items_json", "[]")
        try:
            parsed = json.loads(action_items_json)
            action_items = parsed if isinstance(parsed, list) else []
        except json.JSONDecodeError:
            action_items = []
    
    # Create workbook
    wb = Workbook()
    ws = wb.active
    ws.title = "Action Items"
    
    # Define styles
    header_fill = PatternFill(start_color="6366f1", end_color="6366f1", fill_type="solid")
    title_fill = PatternFill(start_color="7c3aed", end_color="7c3aed", fill_type="solid")
    summary_fill = PatternFill(start_color="f1f5f9", end_color="f1f5f9", fill_type="solid")
    high_fill = PatternFill(start_color="fee2e2", end_color="fee2e2", fill_type="solid")
    low_fill = PatternFill(start_color="dcfce7", end_color="dcfce7", fill_type="solid")
    white_fill = PatternFill(start_color="ffffff", end_color="ffffff", fill_type="solid")
    light_fill = PatternFill(start_color="f8fafc", end_color="f8fafc", fill_type="solid")
    
    thin_border = Border(
        left=Side(style='thin', color='4f46e5'),
        right=Side(style='thin', color='4f46e5'),
        top=Side(style='thin', color='4f46e5'),
        bottom=Side(style='thin', color='4f46e5')
    )
    
    # Row 1: App Title (merged A1:D1)
    ws.merge_cells('A1:D1')
    title_cell = ws['A1']
    title_cell.value = "MeetingMind Report"
    title_cell.font = Font(bold=True, size=16, color="FFFFFF")
    title_cell.fill = title_fill
    title_cell.alignment = Alignment(horizontal='center', vertical='center')
    ws.row_dimensions[1].height = 36
    
    # Row 2: Meeting Summary (merged A2:D2)
    ws.merge_cells('A2:D2')
    summary_cell = ws['A2']
    if meeting_summary and meeting_summary.strip():
        summary_cell.value = f"Meeting Summary: {meeting_summary.strip()}"
    else:
        summary_cell.value = "Meeting Summary: No summary available"
    summary_cell.font = Font(italic=True, size=10, color="334155")
    summary_cell.fill = summary_fill
    summary_cell.alignment = Alignment(horizontal='left', vertical='center', wrap_text=True)
    ws.row_dimensions[2].height = 40
    
    # Row 3: Blank spacer row
    ws.row_dimensions[3].height = 8
    
    # Row 4: Column Headers
    headers = ["Action Item", "Person Responsible", "Deadline", "Priority"]
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=4, column=col)
        cell.value = header
        cell.font = Font(bold=True, size=11, color="FFFFFF")
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal='center', vertical='center')
        cell.border = thin_border
    ws.row_dimensions[4].height = 28
    
    # Data rows (starting from row 5)
    for idx, item in enumerate(action_items):
        if not isinstance(item, dict):
            continue
        
        row = idx + 5
        
        # Alternate row background
        if idx % 2 == 0:
            row_fill = white_fill
        else:
            row_fill = light_fill
        
        # Action Item
        cell_a = ws.cell(row=row, column=1)
        cell_a.value = item.get("action_item", "")
        cell_a.font = Font(size=10, color="1e293b")
        cell_a.fill = row_fill
        cell_a.alignment = Alignment(horizontal='left', vertical='center', wrap_text=True)
        cell_a.border = thin_border
        
        # Person Responsible
        cell_b = ws.cell(row=row, column=2)
        cell_b.value = item.get("person_responsible", "")
        cell_b.font = Font(size=10, color="1e293b")
        cell_b.fill = row_fill
        cell_b.alignment = Alignment(horizontal='left', vertical='center')
        cell_b.border = thin_border
        
        # Deadline
        cell_c = ws.cell(row=row, column=3)
        cell_c.value = item.get("deadline", "")
        cell_c.font = Font(size=10, color="1e293b")
        cell_c.fill = row_fill
        cell_c.alignment = Alignment(horizontal='left', vertical='center')
        cell_c.border = thin_border
        
        # Priority with color coding
        priority = item.get("priority", "Low")
        cell_d = ws.cell(row=row, column=4)
        cell_d.value = priority
        cell_d.border = thin_border
        cell_d.alignment = Alignment(horizontal='left', vertical='center')
        
        if priority == "High":
            cell_d.font = Font(bold=True, size=10, color="dc2626")
            cell_d.fill = high_fill
        else:  # Low
            cell_d.font = Font(bold=True, size=10, color="16a34a")
            cell_d.fill = low_fill
        
        ws.row_dimensions[row].height = 22
    
    # Add 2 blank rows after data
    last_data_row = len(action_items) + 4
    footer_row = last_data_row + 3
    
    # Footer row (merged)
    ws.merge_cells(f'A{footer_row}:D{footer_row}')
    footer_cell = ws.cell(row=footer_row, column=1)
    current_date = datetime.now().strftime("%d %b %Y")
    footer_cell.value = f"Generated by MeetingMind AI  •  {current_date}"
    footer_cell.font = Font(italic=True, size=9, color="94a3b8")
    footer_cell.alignment = Alignment(horizontal='center')
    
    # Column widths
    ws.column_dimensions['A'].width = 55
    ws.column_dimensions['B'].width = 22
    ws.column_dimensions['C'].width = 18
    ws.column_dimensions['D'].width = 14
    
    # Freeze header row (row 4)
    ws.freeze_panes = 'A5'
    
    # Save to buffer
    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    
    return send_file(
        buffer,
        as_attachment=True,
        download_name="meetingmind_action_items.xlsx",
        mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )


# Exempt JSON endpoints from CSRF protection
csrf.exempt(chat)
csrf.exempt(fetch_youtube)
csrf.exempt(export_calendar)
csrf.exempt(transcribe)
csrf.exempt(export_csv)


if __name__ == "__main__":
    app.run(debug=True)
